#A Deployment provides declarative updates for Pods and ReplicaSets.
#You can define Deployments to create new ReplicaSets, or to remove existing Deployments
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  #thus labels are deployment related labels
  labels:
    app: app1
    purpose: ingress
spec:
  selector: 
    matchLabels:
      app: app1
      purpose: ingress
  #pod defintion
  template:
    metadata:
      labels:
        app: app1
        purpose: ingress
    spec:
    - name: app1
      image: guru1188/app1:1.0
------
# This service is used to call nginx Pod
apiVersion: v1
kind: Service
metadata: 
  name: app1
spec: 
  selectors:
    app: app1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
------
#The Ingress lets you map traffic to different backends based on rules you define via the Kubernetes API.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations: #Application Load Balancer will be created based on the annotations in AWS
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/group.name: guru1188
spec:
  ingressClassName: alb #Load Balancer type as Application Load Balancer
  rules:
  - host: "app1.guru97s.cloud" #ALB rule
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: app1 #ALB Target Group, your service name
            port:
              number: 80